service: serverless-onnikka

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x

functions:
  buses:
    handler: index.handler

    events:
      - http:
          path: buses
          method: get
          cors: true
